---
:development:
  :host: '127.0.0.1'
  :port: 2379
  :ca_cert_file: ''
  :client_cert_file: ''
  :client_key_file: ''
  :passphrase: ''

:production:
  :host: '127.0.0.1'
  :port: 2379
  :ca_cert_file: ''
  :client_cert_file: ''
  :client_key_file: ''
  :passphrase: ''


