= pg API Documentation

== debug
[abstract]
--
Description to explain the usage.
--
=== Path
-------------------
GET /clusters/:cluster_id/pg/:pg_id/debug
-------------------

=== Sample curl command
-------------------
curl -XGET
-------------------

=== Sample response
-------------------
{}
-------------------
== deep-scrub
[abstract]
--
Description to explain the usage.
--
=== Path
-------------------
GET /clusters/:cluster_id/pg/:pg_id/deep-scrub
-------------------

=== Sample curl command
-------------------
curl -XGET
-------------------

=== Sample response
-------------------
{}
-------------------
== dump
[abstract]
--
Description to explain the usage.
--
=== Path
-------------------
GET /clusters/:cluster_id/pg/:pg_id/dump
-------------------

=== Sample curl command
-------------------
curl -XGET
-------------------

=== Sample response
-------------------
{}
-------------------
== dump_json
[abstract]
--
Description to explain the usage.
--
=== Path
-------------------
GET /clusters/:cluster_id/pg/:pg_id/dump_json
-------------------

=== Sample curl command
-------------------
curl -XGET
-------------------

=== Sample response
-------------------
{}
-------------------
== dump_pools_json
[abstract]
--
Description to explain the usage.
--
=== Path
-------------------
GET /clusters/:cluster_id/pg/:pg_id/dump_pools_json
-------------------

=== Sample curl command
-------------------
curl -XGET
-------------------

=== Sample response
-------------------
{}
-------------------
== dump_stuck
[abstract]
--
Description to explain the usage.
--
=== Path
-------------------
GET /clusters/:cluster_id/pg/:pg_id/dump_stuck
-------------------

=== Sample curl command
-------------------
curl -XGET
-------------------

=== Sample response
-------------------
{}
-------------------
== force_create_pg 
[abstract]
--
Description to explain the usage.
--
=== Path
-------------------
POST /clusters/:cluster_id/pg/force_create_pg
-------------------

=== Sample curl command
-------------------
curl -XPOST
-------------------

=== Sample response
-------------------
{}
-------------------
== getmap
[abstract]
--
Description to explain the usage.
--
=== Path
-------------------
GET /clusters/:cluster_id/pg/:pg_id/getmap
-------------------

=== Sample curl command
-------------------
curl -XGET
-------------------

=== Sample response
-------------------
{}
-------------------
== ls
[abstract]
--
Description to explain the usage.
--
=== Path
-------------------
GET /clusters/:cluster_id/pg/:pg_id/ls
-------------------

=== Sample curl command
-------------------
curl -XGET
-------------------

=== Sample response
-------------------
{}
-------------------
== ls-by-osd
[abstract]
--
Description to explain the usage.
--
=== Path
-------------------
GET /clusters/:cluster_id/pg/:pg_id/ls-by-osd
-------------------

=== Sample curl command
-------------------
curl -XGET
-------------------

=== Sample response
-------------------
{}
-------------------
== ls-by-pool
[abstract]
--
Description to explain the usage.
--
=== Path
-------------------
GET /clusters/:cluster_id/pg/:pg_id/ls-by-pool
-------------------

=== Sample curl command
-------------------
curl -XGET
-------------------

=== Sample response
-------------------
{}
-------------------
== ls-by-primary
[abstract]
--
Description to explain the usage.
--
=== Path
-------------------
GET /clusters/:cluster_id/pg/:pg_id/ls-by-primary
-------------------

=== Sample curl command
-------------------
curl -XGET
-------------------

=== Sample response
-------------------
{}
-------------------
== map
[abstract]
--
Description to explain the usage.
--
=== Path
-------------------
GET /clusters/:cluster_id/pg/:pg_id/map
-------------------

=== Sample curl command
-------------------
curl -XGET
-------------------

=== Sample response
-------------------
{}
-------------------
== repair
[abstract]
--
Description to explain the usage.
--
=== Path
-------------------
GET /clusters/:cluster_id/pg/:pg_id/repair
-------------------

=== Sample curl command
-------------------
curl -XGET
-------------------

=== Sample response
-------------------
{}
-------------------
== scrub
[abstract]
--
Description to explain the usage.
--
=== Path
-------------------
GET /clusters/:cluster_id/pg/:pg_id/scrub
-------------------

=== Sample curl command
-------------------
curl -XGET
-------------------

=== Sample response
-------------------
{}
-------------------
== set_full_ratio
[abstract]
--
Description to explain the usage.
--
=== Path
-------------------
PUT /clusters/:cluster_id/pg/:pg_id/set_full_ratio
-------------------

=== Sample curl command
-------------------
curl -XPUT
-------------------

=== Sample response
-------------------
{}
-------------------
== set_nearfull_ratio
[abstract]
--
Description to explain the usage.
--
=== Path
-------------------
PUT /clusters/:cluster_id/pg/:pg_id/set_nearfull_ratio
-------------------

=== Sample curl command
-------------------
curl -XPUT
-------------------

=== Sample response
-------------------
{}
-------------------
== stat
[abstract]
--
Description to explain the usage.
--
=== Path
-------------------
GET /clusters/:cluster_id/pg/:pg_id/stat
-------------------

=== Sample curl command
-------------------
curl -XGET
-------------------

=== Sample response
-------------------
{}
-------------------
